# Generated by Django 5.0.3 on 2024-05-11 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='expert',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expert', to=settings.AUTH_USER_MODEL),
        ),
    ]
